ci: racecar fork-testbed patch (chalk/curiosity baseline vs instrumented)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,6 +38,66 @@ env:
 run-name: "Tests ${{ inputs.leg || 'push' }} ${{ inputs.racecar_run }}"
 
 jobs:
+  tests:
+    name: ${{ matrix.os }} ${{ matrix.flavor }}
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - flavor: nvim-0.7
+            runner: ubuntu-22.04
+            os: linux
+            nvim_version: v0.7.0
+          - flavor: nvim-0.8
+            runner: ubuntu-22.04
+            os: linux
+            nvim_version: v0.8.0
+          - flavor: nvim-0.9
+            runner: ubuntu-22.04
+            os: linux
+            nvim_version: v0.9.0
+          - flavor: nvim-0.10
+            runner: ubuntu-22.04
+            os: linux
+            nvim_version: v0.10.0
+          - flavor: nvim-0.11
+            runner: ubuntu-22.04
+            os: linux
+            nvim_version: v0.11.0
+          - flavor: nvim-nightly
+            runner: ubuntu-22.04
+            os: linux
+            nvim_version: nightly
+    runs-on: ${{ matrix.runner }}
+    timeout-minutes: 10
+    steps:
+      - name: Checkout code
+        uses: crashappsec/action-checkout@main
+        with:
+          chalk: ${{ env.CHALK_ON }}
+          profile: ${{ inputs.profile || 'curiosity-tests-racecar' }}
+          observables_continue_on_error: false
+          lfs: false
+      - name: Assert instrumentation is live
+        if: env.CHALK_ON == 'true'
+        run: |
+          test -n "${CURIOSITY_ROOT:-}" || { echo "::error::CURIOSITY_ROOT unset - observables never installed"; exit 1; }
+          test -S "${CURIOSITY_SOCKET_NAME:?socket name unset}" || { echo "::error::co-hostd socket absent"; exit 1; }
+
+      - name: Setup Test Environment
+        run: |
+          mkdir -p ./tmp_home/nvim/pack/vendor/start
+          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ./tmp_home/nvim/pack/vendor/start/plenary.nvim
+          git clone --depth 1 https://github.com/nvim-tree/nvim-web-devicons ./tmp_home/nvim/pack/vendor/start/nvim-web-devicons
+          ln -s $(pwd) ./tmp_home/nvim/pack/vendor/start
+      - name: Setup neovim ${{matrix.nvim_version}}
+        uses: rhysd/action-setup-vim@v1
+        with:
+          neovim: true
+          version: ${{matrix.nvim_version}}
+      - name: Run tests
+        run: |
+          make test
   lint:
     runs-on: ubuntu-22.04
     timeout-minutes: 10
